version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 10     
      java: openjdk8   
    commands:
      - echo Installing Project dependencies
      - mvn install
      - echo Finished Installing Project dependencies
  pre_build:
    commands:
      - echo Testing Java Project
      - npm install --silent
      - java -version
      - mvn test || node result.js
      - cd target/surefire-reports
      - ls
      - echo Finished Testing Java Project
  build:
    commands:
      - echo Building Project
      - ng build
      - echo Finished Building

cache:
  paths:
    - 'node_modules/**/*'
